version: '3.7'
services:
  mariadb:
    image: library/mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/conf:/etc/mysql/conf.d
      - ./db/csv:/tmp/csv